name: Test, Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Log in to Docker Hub
        run: |
          printf "%s" "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Pull Backend Image
        run: |
          docker pull $DOCKERHUB_USERNAME/backend:dev-latest || true

      - name: Build and Push Backend Image
        run: |
          docker tag $DOCKERHUB_USERNAME/backend:dev-latest $DOCKERHUB_USERNAME/backend:latest
          docker push $DOCKERHUB_USERNAME/backend:latest

      - name: Pull Frontend Image
        run: |
          docker pull $DOCKERHUB_USERNAME/frontend:dev-latest || true

      - name: Build and Push Frontend Image
        run: |
          docker tag $DOCKERHUB_USERNAME/frontend:dev-latest $DOCKERHUB_USERNAME/frontend:latest
          docker push $DOCKERHUB_USERNAME/frontend:latest
