name: CI / Lint / Tests / Security


on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:

  sast-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST Scan
        run: |
          semgrep scan --config auto --sarif --output semgrep.sarif || true

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "semgrep.sarif"

  test_backend:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        working-directory: Backend/App
        run: |
          pip install -r requirements.txt
      

      - name: Run Xenon Complexity Check
        working-directory: Backend
        run: |
          xenon . --max-absolute C --max-modules C --max-average C

      - name: Generate Radon reports
        working-directory: Backend
        run: |
          radon cc . -s -j > radon_report.json
          radon cc . -s > radon_report.txt
          radon mi . -s > radon_mi_report.txt

      - name: Upload Radon reports
        uses: actions/upload-artifact@v4
        with:
          name: radon-complexity-reports
          path: |
            Backend/radon_report.json
            Backend/radon_report.txt
            Backend/radon_mi_report.txt


      - name: Run Bandit Security Scan
        run: |
          bandit -r Backend -x Backend/Pytest -f html -o bandit_report.html || true
          bandit -r Backend -x Backend/Pytest -f json -o bandit_report.json || true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: |
            bandit_report.html
            bandit_report.json

      - name: Run backend tests with coverage
        working-directory: Backend
        run: |
          coverage run --branch -m pytest -v
          coverage report -m
          coverage html -d ./Pytest/coverage_report

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: Backend/Pytest/coverage_report


  test_frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: Frontend/GeoDummy
        run: npm ci

      - name: Run ESLint
        working-directory: Frontend/GeoDummy
        run: npm run lint

      - name: Run frontend unit tests
        working-directory: Frontend/GeoDummy
        run: npm run test

  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [test_backend,test_frontend, sast-scan]

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          printf "%s" "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Get version number
        id: version
        run: |
          VERSION=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$VERSION" ]; then
            VERSION="0.1.0"
          else
            IFS='.' read -r major minor patch <<< "${VERSION//v/}"
            patch=$((patch+1))
            VERSION="$major.$minor.$patch"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/backend:${{ steps.version.outputs.version }} ./Backend/App
          docker push $DOCKERHUB_USERNAME/backend:${{ steps.version.outputs.version }}
          docker tag $DOCKERHUB_USERNAME/backend:${{ steps.version.outputs.version }} $DOCKERHUB_USERNAME/backend:dev-latest
          docker push $DOCKERHUB_USERNAME/backend:dev-latest

      - name: Build and Push Frontend Image
        run: |
          cd Frontend/GeoDummy
          npm ci
          npm run build
          cd ../../
          docker build -t $DOCKERHUB_USERNAME/frontend:${{ steps.version.outputs.version }} ./Frontend/GeoDummy
          docker push $DOCKERHUB_USERNAME/frontend:${{ steps.version.outputs.version }}
          docker tag $DOCKERHUB_USERNAME/frontend:${{ steps.version.outputs.version }} $DOCKERHUB_USERNAME/frontend:dev-latest
          docker push $DOCKERHUB_USERNAME/frontend:dev-latest

