name: Unit tests on push branch dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test_backend:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd Backend/Pytest
          python -m venv venv
          source venv/bin/activate
          pip install -r ../requirements.txt

      - name: Run Bandit Security Scan
        run: |
          cd Backend/Pytest
          source venv/bin/activate
          bandit -r ../ -x venv -f html -o bandit_report.html
          bandit -r ../ -x venv -f json -o bandit_report.json

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: |
            Backend/Pytest/bandit_report.html
            Backend/Pytest/bandit_report.json

      - name: Run tests
        run: |
          cd Backend/Pytest
          source venv/bin/activate
          coverage run --branch -m pytest -v
          coverage report -m
          coverage html -d ./coverage_report
      
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: Backend/Pytest/coverage_report


  test_frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Frontend/GeoDummy
          npm ci

      - name: Run unit tests
        run: |
          cd Frontend/GeoDummy
          npm run lint
          npm run test